openapi: 3.0.0
info:
  title: myapi2
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /users:
    get:
      summary: the get
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: modelX
                type: object
                properties:
                  id:
                    type: string
                  Yattr:
                    title: ModelY
                    type: object
                    properties:
                      id:
                        type: string
                      attr:
                        type: string
              examples: {}
            application/xml:
              schema:
                title: modelX
                type: object
                properties:
                  id:
                    type: string
                  Yattr:
                    title: ModelY
                    type: object
                    properties:
                      id:
                        type: string
                      attr:
                        type: string
              examples:
                example-1: {}
      requestBody:
        content:
          application/json:
            schema:
              title: ModelY
              type: object
              properties:
                id:
                  type: string
                attr:
                  type: string
        description: |
          A test request
components:
  schemas:
    user:
      title: user
      type: object
      properties:
        id:
          type: string
      description: a user
